DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;
USE blog;
DROP TABLE IF EXISTS blog;

SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;
 
CREATE TABLE blog (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title TEXT NOT NULL
)DEFAULT CHARACTER SET=utf8;
 
INSERT INTO blog (title) VALUES ("ブログ1"),("ブログ2"),("ブログ3");